### ISSUE TITLE
Course: Introduction to Machine Learning with scikit-learn

### ISSUE THREAD

**Issue by justmarkham** [dair-ai/ML-YouTube-Courses#2]
Hello! Before I submit a PR, I wanted to ask if you would be interested in adding my ML course?

Playlist: [Introduction to Machine Learning with scikit-learn](https://www.youtube.com/playlist?list=PL5-da3qGB5ICeMbQuqbbCOQWcS6OYBr5A)

It has 2.1 million views across the 11 videos. If you'd like to read some of the comments people have left about the course, please scroll to the "Comments from my students" section on [this page](https://courses.dataschool.io/introduction-to-machine-learning-with-scikit-learn). (That page also lists all of the topics that are covered in the course.)

It is not a recent course, since I posted it in 2015 and 2016. However, very little has changed in the scikit-learn API since 2015 that is relevant to the course, and all of the ML principles I teach in the course are still up-to-date and relevant. As well, I updated all of the code (and fixed any outdated links) in the course's [GitHub repository](https://github.com/justmarkham/scikit-learn-videos) earlier this year.

If you'd like me to add the course, I'm happy to submit a PR. But if this doesn't match what you are looking for, no worries at all!

Thanks!

**Comment by omarsar** [comment]
Hi, @justmarkham thanks for opening this. It's really good content. After thinking about this for a bit, I have decided to stick to newer courses for now (2020, 2021, and so on). I am still open to the idea of expanding the repo but will keep it strict for now (i.e., consider newer courses only).

**Comment by justmarkham** [comment]
@omarsar That's totally fine, thanks for your consideration and for following up! 👍

**Comment by dorothea101** [comment]
Is this closed?
